workflows:
  ios-workflow:
      name: iOS Workflow
      integrations:
        app_store_connect: G8 Ios Connect
      environment:
        vars:
          APP_ID: 6447049318
        ios_signing:
          provisioning_profiles:
            - G8_Pro_Cert
          certificates:
            - G8_Sign_Cert
      scripts:
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Get Flutter packages
          script: |
            flutter packages pub get
        - name: Install pods
          script: |
            find . -name "Podfile" -execdir pod install \;
        - name: Flutter build ipa
          script: |
            BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
            flutter build ipa --export-options-plist ios/export.plist --build-number=$BUILD_NUMBER --build-name=1.0.0 --release
      artifacts:
        - build/ios/ipa/*.ipa
      publishing:
        email:
          recipients:
            - chaudanghuy@gmail.com
          notify:
            success: true
            failure: false
        app_store_connect:
          auth: integration
          submit_to_testflight: true
          submit_to_app_store: true